### ISSUE TITLE
Convert message-notes-plus notes to XNote++

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [alehro/message-notes-plus#3]
- install XNote++ by Lorenz Froihofer or QNote by Martins Lazdans, check if it meets your requirements.
- look for messagenotesplus.sqlite in your Thunderbird profile folder "C:\Users\<user>\AppData\Roaming\Thunderbird\Profiles\xyz123.default\" 
- open your messagenotesplus.sqlite and export table 'messagenotes' to messagenotesplus.csv
  I used SQLiteStudio (https://sqlitestudio.pl/index.rvt) to export to messagenotesplus.csv, using: 
  Tools / Export: single table (messagenotes), export table data only, text encoding UTF-8, column names in first row, seperator semicolon (;)
- open messagenotesplus.csv (using any text editor) and replace any control characters (tabs 0x09 etc.) you find by spaces
   Control characters will otherwise later show as strange characters in your newly created XNote++/QNote notes (but are otherwise harmless).
- extract files from [MNPConverter.zip](https://github.com/alehro/message-notes-plus/files/3820704/MNPConverter.zip), I've run the zip file through virustotal.com, see 
https://www.virustotal.com/file/44e86a4f3c2cbe813dbeb9c894934be5f8710a916924f5d6d04e883601c6a39a/analysis/
to check yourself.
- you may try the following steps first with my sample files included in MNPConverter.zip
- open (attached) messagenotesplus.ods (using LibreOffice) and paste messagenotesplus.csv starting from cell A1.
    Check columns P, Q if they show a reasonable timestamp and your notes texts (URL encoded) respectively.
    If you have more than 1000 notes copy the formulas in columns P, Q (currently there are 1000 rows for 1000 notes).
- In LibreOffice select from the menu: Extras / Macros / Run macro: click open messagenotesplus.ods on the left pane, 
  click open Standard, select MessageNotesPlus, select ExportFiles from the right pane, click run button to execute 
  macro ExportFiles. This creates XNote+ files in a folder .\XNoteFiles below the folder where messagenotesplus.ods 
  is located.
- copy the generated files in .\XNoteFiles to the \XNote folder in your Thunderbird profile folder, "C:\Users\<user>\AppData\Roaming\Thunderbird\Profiles\xyz123.default\XNote" 
   You cannot damage anything, XNote++/QNote will silently ignore .xnote files it cannot process. 
- your MessageNotesPlus notes will re-appear as XNote++/QNote notes (create a column 'XNote' in Thunderbird to see which mails have notes)
- Enjoy!

**Comment by jamaisx** [comment]
Well, it works, thank you! Recovered all the notes but since the long awaited solution they are almost useless :-(

**Comment by Sensor66** [comment]
Thanks for this procedure and macros! 
It works fine on my Win10 with Thunderbird 68.2.2 (64-bit) with XNote++ version 2.3.1. 
(Only instances where it kind of fails is when there are "/" in the message-ID: they get broken up into subfolders, understandably.)
Btw, a tip to find your mnp-notes and check if they were replaced by a XNote: 
in TB, search for their old **Tag** = "mnp-note". 
Some do not get replaced and can be manually searched by checking their message-ID (in TB: view source) against the IDs in the messagenotesplus.ods.

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks for your observation and tipps, Sensor66!
Regarding the "/" you could add another ReplaceSet() line after 
`sFileName = ReplaceSet(sFileName, "$", "%24")`
in macro `ExportFiles` to replace slashes, e.g.
`sFileName = ReplaceSet(sFileName, "/", "%2F")`
Maybe there are even more non-file name characters in message-IDs.

**Comment by SallyB500** [comment]
I have followed the above instructions, but am stuck at "run macro ExportFiles from messagenotesplus.ods/Standard/MessageNotesPlus, this creates XNote++ files in a folder .\XNoteFiles below the folder where messagenotesplus.ods is located"
Where is the macro ExportFiles, and how do I run it?
Thanks!

**Comment by ThomasHeinrichSchmidt** [comment]
Extract files from [MNPConverter.zip](https://github.com/alehro/message-notes-plus/files/3820704/MNPConverter.zip), open messagenotesplus.ods from MNPConverter.zip file using OpenOffice, confirm to use macros, paste messagenotesplus.csv starting from cell A1. In OpenOffice select from the menu: Extras / Macros / Run macro: click open messagenotesplus.ods on the left pane, click open Standard, select MessageNotesPlus, select ExportFiles from the right pane, click run button to execute macro ExportFiles. 
I'm using the German version of LibreOffice so words can slightly differ.

**Comment by SallyB500** [comment]
Thank you so much for your help.  If I open the .ods file in openoffice, Column P gives me an Err:517 and Column Q gives me a #NAME?  If I open the .ods file in Excell, column P and Q work fine, but the macro doesn't.  What am I doing wrong in Openoffice?
Thank you!

**Comment by ThomasHeinrichSchmidt** [comment]
When I open messagenotesplus.ods I see 5 sample lines that I included to show what the lines from messagenotesplus.csv should be looking like after pasting them. In columns P and Q of these sample lines you should be seeing the Date and the URL-Encoded string of the respective XNote entries, like this
![ColumnsPQ](https://user-images.githubusercontent.com/8068047/156154924-fbb3d0d5-b83a-44e1-a1d2-20b76e80170a.jpg)
If you do not see this there is something wrong with your OpenOffice, maybe you could try LibreOffice instead. I have no idea why messagenotesplus.ods would be giving you an Err:517/#NAME?.
Before you paste your messagenotesplus.csv (coming from messagenotesplus.sqlite export table 'messagenotes') have a look at this file first. Does it have the same header as my sample messagenotesplus.csv I included in MNPConverter.zip? 
![messagenotesplus-csv](https://user-images.githubusercontent.com/8068047/156156371-f7ba5d93-80fc-492b-89b6-5ef40687c146.jpg)
If it does do the texts in the 'note' column look similar to the respective column in my sample messagenotesplus.csv, like this?
`"{""body"":""Message Notes Plus  #5"",""date"":1485873041685,""status"":0}"`
If it doesn't something went wrong with the export from your messagenotesplus.sqlite database file.

**Comment by SallyB500** [comment]
Using LibreOffice was the key!  Thanks.  One more thing, I have some message IDs that end in == (exp: 1520865527md5:f4eW+1GJvX3xS7j5oBvOiw==)  That stops the macro with a "BASIC runtime error. An exception occurred 
Type: com.sun.star.ucb.ContentCreationException 
Message: Unable to create Content for <file:///C:/MNPConverter/XNoteFiles/1520865527md5:f4eW+1GJvX3xS7j5oBvOiw==.xnote>: .

any idea?  Thank you SO much

**Comment by ThomasHeinrichSchmidt** [comment]
Yes, but I think the cause is rather the colon in your message ID and not the equal sign. I could encode the colon (and spaces) in the macro code like this
![ExportFiles-changes](https://user-images.githubusercontent.com/8068047/156335885-a9c952fb-327e-42db-a470-622bafaba4e0.png)
But I am not sure if XNote++ will actually recognize note files with names constructed like this. Depends on how XNote++ internally handles message IDs with colons and spaces. 
Anyway I have prepared a new [MNPConverter2.zip](https://github.com/alehro/message-notes-plus/files/8168888/MNPConverter2.zip) with a macro changed accordingly. 
Instead (or alternatively) you may remove those rows from messagenotesplus.ods with "bad" message IDs.

**Comment by SallyB500** [comment]
That did it!  You're a genius!  Thank you SOOOOO much!  It is much appreciated!
